# This is a basic workflow to help you get started with Actions

name: pytest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "pytest"      
    pytest:
      runs-on: ubuntu-latest
      name: Pytest passing tests
      steps:
        - uses: actions/setup-python@v2
          with:
            python-version: '3.7.x'
        - name: Checkout
          uses: actions/checkout@v2
        - name: Pytest Action Step
          id: pytest
          uses: paolorechia/fast-pytest-github-action@develop
          with:
            pytest_args: .  # 'sample_py/test_success.py'
            requirements_file: 'requirements.txt'
